const categories = [
  { name: "Art", isSelected: true },
  { name: "Education", isSelected: true },
  { name: "Games", isSelected: true },
  { name: "Movies", isSelected: true },
  { name: "News", isSelected: true },
  { name: "Religion", isSelected: true },
  { name: "Social", isSelected: true },
  { name: "Politic", isSelected: true },
  { name: "Health", isSelected: true },
  { name: "Animals", isSelected: true },
  { name: "Music", isSelected: true },
  { name: "Philosophy", isSelected: true },
  { name: "Sports", isSelected: true },
  { name: "Technology", isSelected: true },
  { name: "Nature", isSelected: true },
  { name: "Science", isSelected: true },
  { name: "Books", isSelected: true },
  { name: "Cars", isSelected: true },
  { name: "Irrelevant", isSelected: true },
];

const categoriesWithEmoji = {
  Art: "🎨",
  Education: "🏫",
  Games: "🎮",
  Movies: "🍿",
  News: "📰",
  Religion: "🕯️",
  Social: "👫",
  Politic: "⚖️",
  Health: "⚕️",
  Animals: "🐶",
  Music: "🎵",
  Philosophy,
  Sports: "🏀",
  Technology: "🤖",
  Nature: "🌳",
  Science: "🧬",
  Books: "📖",
  Cars: "🚗",
  Irrelevant: "🏷️",
};

export { categories, categoriesWithEmoji };
